apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8081']
      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8082']
      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8080']
