spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8080/
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082/
          predicates:
            - Path=/api/orders/**
  application:
    name: api-gateway
  metrics:
    export:
      prometheus:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8081
